stages:
  - test
  - benchmark

test:
  stage: test
  tags:
    - amd64
  image: eclipse-temurin:25-jdk
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - .gradle/wrapper
      - .gradle/caches
    policy: pull-push
  script:
    - ./gradlew --no-daemon test jmhTest
  artifacts:
    when: always
    reports:
      junit:
        - build/test-results/test/TEST-*.xml
        - build/test-results/jmhTest/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: build/reports/jacoco/test/jacocoTestReport.xml
    paths:
      - build/reports/tests/test/
      - build/reports/jacoco/
    expire_in: 1 week
  coverage: '/Coverage:\s*([0-9.]+)%/'
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: always

jmh-smoke:
  stage: benchmark
  tags:
    - amd64
  image: eclipse-temurin:25-jdk
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  cache:
    key:
      files:
        - gradle/wrapper/gradle-wrapper.properties
    paths:
      - .gradle/wrapper
      - .gradle/caches
    policy: pull-push
  script:
    - ./gradlew --no-daemon jmhSmoke
  artifacts:
    when: always
    paths:
      - build/jmh/
    expire_in: 1 week
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: never
    - when: always